apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

commonLabels:
    app: api-hub
    env: staging

bases:
  - ../../../base

resources:
  - ingress.yaml

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

namespace: staging