apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

commonLabels:
    app: api-hub
    env: staging

bases:
  - ../../../base

patchesStrategicMerge:
  - deployment.yaml

namespace: staging