name: Docker build and push to staging

on:
  workflow_dispatch:
    inputs:
      runner_number:
        description: github runner number.
        required: true
        default: "1"
  push:
    branches:
      - main
      - staging
  pull_request:

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  GKE_REGION: ${{ secrets.GKE_REGION }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  CLUSTER_NAME: ${{secrets.GKE_CLUSTER_STAGING}}
  IMAGE: api-hub
  IMAGE_TAG: "staging-$(date +'%Y%m%d')-${{github.run_number}}"
  ECR_STAGING: ${{ secrets.ECR_STAGING }}
jobs:
  setup-build-publish-deploy:
    defaults:
      run:
        shell: bash
        working-directory: ./
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: '${{env.CLUSTER_NAME}}'
        location: ${{ env.GKE_REGION }}

    - uses: yokawasa/action-setup-kube-tools@v0.11.1
      with:
        setup-tools: |
          kubectl: '1.25'
          kustomize: '5.0.0'
          helm: '3.11.1'
          kubeconform: '0.5.0'
          
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: "ropay-gks-cluster-staging"	
        location: "europe-west2"